// Generated by pgd. Do not edit.
package example.db

enum class Mood(val label: String) {
    SAD("sad"),
    OK("ok"),
    HAPPY("happy"),
    OVER_THE_MOON("over the moon"),
    ;

    companion object {
        fun fromLabel(label: String): Mood =
            entries.firstOrNull { it.label == label }
                ?: error("'$label' is not a value of Postgres enum mood")
    }
}
