// Generated by pgd from events.sql. Do not edit.
package example.db

import java.sql.Connection
import java.sql.Types
import java.time.OffsetDateTime
import org.postgresql.PGConnection
import org.postgresql.copy.PGCopyOutputStream

data class BulkLoadEventsRow(
    val userId: Long,
    val name: String,
    val note: String?,
    val feeling: Mood,
)

private const val BULK_LOAD_EVENTS: String =
    "COPY events (user_id, name, note, feeling) FROM STDIN"

/**
 * ```sql
 * COPY events (user_id, name, note, feeling) FROM STDIN
 * ```
 */
fun Connection.bulkLoadEvents(rows: Iterable<BulkLoadEventsRow>): Long {
    val copy = PGCopyOutputStream(unwrap(PGConnection::class.java), BULK_LOAD_EVENTS)
    try {
        val out = copy.bufferedWriter()
        for (row in rows) {
            out.write(pgdCopyText(row.userId))
            out.write("\t")
            out.write(pgdCopyText(row.name))
            out.write("\t")
            out.write(pgdCopyText(row.note))
            out.write("\t")
            out.write(pgdCopyText(row.feeling.label))
            out.write("\n")
        }
        out.flush()
        return copy.endCopy()
    } catch (e: Throwable) {
        // Leaving the connection mid-COPY would break every later statement.
        runCatching { copy.cancelCopy() }
        throw e
    }
}

data class RecordEventRow(
    val id: Long,
    val happened: OffsetDateTime,
)

private const val RECORD_EVENT: String =
    "INSERT INTO events (user_id, name, feeling)\n" +
        "VALUES (? ::bigint, ? ::text, ? ::mood)\n" +
        "RETURNING id, happened"

/**
 * ```sql
 * INSERT INTO events (user_id, name, feeling)
 * VALUES ($1::bigint, $2::text, $3::mood)
 * RETURNING id, happened
 * ```
 */
fun <T : Any> Connection.recordEvent(
    userId: Long,
    name: String,
    feeling: Mood,
    mapper: (
        id: Long,
        happened: OffsetDateTime,
    ) -> T,
): T =
    prepareStatement(RECORD_EVENT).use { statement ->
        statement.setLong(1, userId)
        statement.setString(2, name)
        statement.setObject(3, feeling.label, Types.OTHER)
        statement.executeQuery().use { resultSet ->
            check(resultSet.next()) {
                "RecordEvent is declared :exactlyone but matched no rows"
            }
            val row = mapper(
                resultSet.getLong(1),
                checkNotNull(resultSet.getObject(2, OffsetDateTime::class.java)),
            )
            check(!resultSet.next()) {
                "RecordEvent is declared :exactlyone but matched more than one row"
            }
            row
        }
    }

/** Maps each row to [RecordEventRow]. */
fun Connection.recordEvent(userId: Long, name: String, feeling: Mood): RecordEventRow =
    recordEvent(userId, name, feeling, ::RecordEventRow)

private const val ANNOTATE_EVENT: String =
    "UPDATE events SET note = ? ::text WHERE id = ? ::bigint"

/**
 * ```sql
 * UPDATE events SET note = $2::text WHERE id = $1::bigint
 * ```
 */
fun Connection.annotateEvent(id: Long, note: String): Int =
    prepareStatement(ANNOTATE_EVENT).use { statement ->
        statement.setString(1, note)
        statement.setLong(2, id)
        statement.executeUpdate()
    }

data class AnnotateEventParams(
    val id: Long,
    val note: String,
)

/** Batched form of [annotateEvent]. */
fun Connection.annotateEventBatch(rows: Iterable<AnnotateEventParams>): IntArray =
    prepareStatement(ANNOTATE_EVENT).use { statement ->
        for (row in rows) {
            statement.setString(1, row.note)
            statement.setLong(2, row.id)
            statement.addBatch()
        }
        statement.executeBatch()
    }

private const val COUNT_EVENTS: String =
    "SELECT count(*) FROM events"

/**
 * ```sql
 * SELECT count(*) FROM events
 * ```
 */
fun Connection.countEvents(): Long =
    prepareStatement(COUNT_EVENTS).use { statement ->
        statement.executeQuery().use { resultSet ->
            check(resultSet.next()) {
                "CountEvents is declared :exactlyone but matched no rows"
            }
            val row = resultSet.getLong(1)
            check(!resultSet.next()) {
                "CountEvents is declared :exactlyone but matched more than one row"
            }
            row
        }
    }

private const val EVENT_NAMES: String =
    "SELECT name FROM events WHERE user_id = ? ::bigint ORDER BY id"

/**
 * ```sql
 * SELECT name FROM events WHERE user_id = $1::bigint ORDER BY id
 * ```
 */
fun Connection.eventNames(userId: Long): List<String> =
    prepareStatement(EVENT_NAMES).use { statement ->
        statement.setLong(1, userId)
        statement.executeQuery().use { resultSet ->
            val rows = ArrayList<String>()
            while (resultSet.next()) {
                rows += checkNotNull(resultSet.getString(1))
            }
            rows
        }
    }
