// Generated by pgd. Do not edit.
package example.db

/**
 * Renders one value as a field in COPY text format.
 *
 * NULL is the two-character sequence \N, and backslash, tab, newline
 * and carriage return are escaped so they cannot end the field or the
 * row early.
 */
internal fun pgdCopyText(value: Any?): String = when (value) {
    null -> "\\N"
    is Boolean -> if (value) "t" else "f"
    is ByteArray -> "\\\\x" + value.joinToString("") { "%02x".format(it) }
    else -> value.toString()
        .replace("\\", "\\\\")
        .replace("\t", "\\t")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
}
