// Generated by pgd from preferences.sql. Do not edit.
package example.db

import java.sql.Connection
import java.sql.Types

private const val SET_PREFERENCES: String =
    "INSERT INTO preferences (user_id, mood, tags, settings)\n" +
        "VALUES (? ::bigint, ? ::mood, ? ::text[], ? ::jsonb)\n" +
        "ON CONFLICT (user_id) DO UPDATE\n" +
        "SET mood = EXCLUDED.mood,\n" +
        "    tags = EXCLUDED.tags,\n" +
        "    settings = EXCLUDED.settings"

/**
 * ```sql
 * INSERT INTO preferences (user_id, mood, tags, settings)
 * VALUES ($1::bigint, $2::mood, $3::text[], $4::jsonb)
 * ON CONFLICT (user_id) DO UPDATE
 * SET mood = EXCLUDED.mood,
 *     tags = EXCLUDED.tags,
 *     settings = EXCLUDED.settings
 * ```
 */
fun Connection.setPreferences(userId: Long, mood: Mood, tags: List<String?>, settings: String) {
    prepareStatement(SET_PREFERENCES).use { statement ->
        statement.setLong(1, userId)
        statement.setObject(2, mood.label, Types.OTHER)
        statement.setArray(3, createArrayOf("text", tags.toTypedArray()))
        statement.setString(4, settings)
        statement.execute()
    }
}

data class FindPreferencesRow(
    val userId: Long,
    val mood: Mood,
    val tags: List<String?>,
    val contact: String?,
    val sessionLength: String?,
    val settings: String,
)

private const val FIND_PREFERENCES: String =
    "SELECT user_id, mood, tags, contact, session_length, settings\n" +
        "FROM preferences\n" +
        "WHERE user_id = ? ::bigint"

/**
 * ```sql
 * SELECT user_id, mood, tags, contact, session_length, settings
 * FROM preferences
 * WHERE user_id = $1::bigint
 * ```
 */
fun <T : Any> Connection.findPreferences(
    userId: Long,
    mapper: (
        userId: Long,
        mood: Mood,
        tags: List<String?>,
        contact: String?,
        sessionLength: String?,
        settings: String,
    ) -> T,
): T? =
    prepareStatement(FIND_PREFERENCES).use { statement ->
        statement.setLong(1, userId)
        statement.executeQuery().use { resultSet ->
            if (!resultSet.next()) {
                null
            } else {
                val row = mapper(
                    resultSet.getLong(1),
                    Mood.fromLabel(checkNotNull(resultSet.getString(2))),
                    checkNotNull(resultSet.getArray(3)).let { array -> (array.array as Array<*>).map { it as String? } },
                    resultSet.getString(4),
                    resultSet.getString(5),
                    checkNotNull(resultSet.getString(6)),
                )
                check(!resultSet.next()) {
                    "FindPreferences is declared :one but matched more than one row"
                }
                row
            }
        }
    }

/** Maps each row to [FindPreferencesRow]. */
fun Connection.findPreferences(userId: Long): FindPreferencesRow? =
    findPreferences(userId, ::FindPreferencesRow)

private const val USERS_IN_MOOD: String =
    "SELECT user_id\n" +
        "FROM preferences\n" +
        "WHERE mood = ? ::mood\n" +
        "ORDER BY user_id"

/**
 * ```sql
 * SELECT user_id
 * FROM preferences
 * WHERE mood = $1::mood
 * ORDER BY user_id
 * ```
 */
fun Connection.usersInMood(mood: Mood): List<Long> =
    prepareStatement(USERS_IN_MOOD).use { statement ->
        statement.setObject(1, mood.label, Types.OTHER)
        statement.executeQuery().use { resultSet ->
            val rows = ArrayList<Long>()
            while (resultSet.next()) {
                rows += resultSet.getLong(1)
            }
            rows
        }
    }
