// Generated by pgd from users.sql. Do not edit.
package example.db

import java.sql.Connection
import java.time.OffsetDateTime

data class FindActiveUsersRow(
    val id: Long?,
    val email: String?,
    val displayName: String?,
    val totalCents: Int?,
)

private const val FIND_ACTIVE_USERS: String =
    "SELECT u.id, u.email, u.display_name, o.total_cents\n" +
        "FROM users u\n" +
        "LEFT JOIN orders o ON o.user_id = u.id\n" +
        "WHERE u.active AND u.created_at > ? ::timestamptz\n" +
        "ORDER BY u.created_at DESC"

/**
 * ```sql
 * SELECT u.id, u.email, u.display_name, o.total_cents
 * FROM users u
 * LEFT JOIN orders o ON o.user_id = u.id
 * WHERE u.active AND u.created_at > $1::timestamptz
 * ORDER BY u.created_at DESC
 * ```
 */
fun <T : Any> Connection.findActiveUsers(
    since: OffsetDateTime,
    mapper: (
        id: Long?,
        email: String?,
        displayName: String?,
        totalCents: Int?,
    ) -> T,
): List<T> =
    prepareStatement(FIND_ACTIVE_USERS).use { statement ->
        statement.setObject(1, since)
        statement.executeQuery().use { resultSet ->
            val rows = ArrayList<T>()
            while (resultSet.next()) {
                rows += mapper(
                    resultSet.getLong(1).takeUnless { resultSet.wasNull() },
                    resultSet.getString(2),
                    resultSet.getString(3),
                    resultSet.getInt(4).takeUnless { resultSet.wasNull() },
                )
            }
            rows
        }
    }

/** Maps each row to [FindActiveUsersRow]. */
fun Connection.findActiveUsers(since: OffsetDateTime): List<FindActiveUsersRow> =
    findActiveUsers(since, ::FindActiveUsersRow)

data class FindUserByEmailRow(
    val id: Long,
    val email: String,
    val displayName: String?,
    val createdAt: OffsetDateTime,
)

private const val FIND_USER_BY_EMAIL: String =
    "SELECT id, email, display_name, created_at\n" +
        "FROM users\n" +
        "WHERE email = ? ::text"

/**
 * ```sql
 * SELECT id, email, display_name, created_at
 * FROM users
 * WHERE email = $1::text
 * ```
 */
fun <T : Any> Connection.findUserByEmail(
    email: String,
    mapper: (
        id: Long,
        email: String,
        displayName: String?,
        createdAt: OffsetDateTime,
    ) -> T,
): T? =
    prepareStatement(FIND_USER_BY_EMAIL).use { statement ->
        statement.setString(1, email)
        statement.executeQuery().use { resultSet ->
            if (!resultSet.next()) {
                null
            } else {
                val row = mapper(
                    resultSet.getLong(1),
                    checkNotNull(resultSet.getString(2)),
                    resultSet.getString(3),
                    checkNotNull(resultSet.getObject(4, OffsetDateTime::class.java)),
                )
                check(!resultSet.next()) {
                    "FindUserByEmail is declared :one but matched more than one row"
                }
                row
            }
        }
    }

/** Maps each row to [FindUserByEmailRow]. */
fun Connection.findUserByEmail(email: String): FindUserByEmailRow? =
    findUserByEmail(email, ::FindUserByEmailRow)

data class InsertUserRow(
    val id: Long,
    val createdAt: OffsetDateTime,
)

private const val INSERT_USER: String =
    "INSERT INTO users (email, display_name)\n" +
        "VALUES (? ::text, ? ::text)\n" +
        "RETURNING id, created_at"

/**
 * ```sql
 * INSERT INTO users (email, display_name)
 * VALUES ($1::text, $2::text)
 * RETURNING id, created_at
 * ```
 */
fun <T : Any> Connection.insertUser(
    email: String,
    displayName: String,
    mapper: (
        id: Long,
        createdAt: OffsetDateTime,
    ) -> T,
): T? =
    prepareStatement(INSERT_USER).use { statement ->
        statement.setString(1, email)
        statement.setString(2, displayName)
        statement.executeQuery().use { resultSet ->
            if (!resultSet.next()) {
                null
            } else {
                val row = mapper(
                    resultSet.getLong(1),
                    checkNotNull(resultSet.getObject(2, OffsetDateTime::class.java)),
                )
                check(!resultSet.next()) {
                    "InsertUser is declared :one but matched more than one row"
                }
                row
            }
        }
    }

/** Maps each row to [InsertUserRow]. */
fun Connection.insertUser(email: String, displayName: String): InsertUserRow? =
    insertUser(email, displayName, ::InsertUserRow)

private const val DEACTIVATE_STALE_USERS: String =
    "UPDATE users\n" +
        "SET active = false\n" +
        "WHERE created_at < ? ::timestamptz"

/**
 * ```sql
 * UPDATE users
 * SET active = false
 * WHERE created_at < $1::timestamptz
 * ```
 */
fun Connection.deactivateStaleUsers(cutoff: OffsetDateTime): Int =
    prepareStatement(DEACTIVATE_STALE_USERS).use { statement ->
        statement.setObject(1, cutoff)
        statement.executeUpdate()
    }
