package io.pgdescribe.core

import kotlin.io.path.nameWithoutExtension

public data class GeneratedFile(
    /** Path relative to the output directory, including the package directories. */
    val relativePath: String,
    val contents: String,
)

public data class CodeGenConfig(
    val packageName: String = PgdConfig.DEFAULT_PACKAGE,
    /** Postgres type name to another Postgres type name, from `pgd.toml`. */
    val typeAliases: Map<String, String> = emptyMap(),
)

private data class Param(
    val name: String,
    val type: ResolvedType,
    /** The `$n` this parameter corresponds to. */
    val index: Int,
)

private data class Column(
    val property: String,
    val type: ResolvedType,
    val nullable: Boolean,
    val index: Int,
) {
    val kotlinType: String get() = type.kotlin + if (nullable) "?" else ""
}

/**
 * Emits the most boring JDBC code possible: `PreparedStatement`, `ResultSet`,
 * data classes, extension functions on `java.sql.Connection`. No runtime
 * library, no driver abstraction, nothing to learn.
 */
internal object CodeGenerator {

    /** Where a generated signature stops fitting on one line. */
    private const val MAX_LINE = 100

    fun generate(
        queries: List<AnalyzedQuery>,
        config: CodeGenConfig,
        registry: TypeRegistry,
    ): Pair<GeneratedFile?, List<Diagnostic>> {
        val diagnostics = mutableListOf<Diagnostic>()
        val source = queries.first().query.file
        val models = queries.mapNotNull { analyzed ->
            val (model, problems) = modelOf(analyzed, registry)
            diagnostics += problems
            model
        }
        if (models.isEmpty() || diagnostics.any { it.severity == Severity.ERROR }) {
            return null to diagnostics
        }

        val imports = sortedSetOf("java.sql.Connection")
        models.forEach { imports += it.imports }

        val out = StringBuilder()
        out.append("// Generated by pgd from ${source.fileName}. Do not edit.\n")
        out.append("package ${config.packageName}\n\n")
        imports.forEach { out.append("import $it\n") }
        out.append('\n')

        models.forEachIndexed { index, model ->
            if (index > 0) out.append('\n')
            out.append(model.text)
        }

        val directory = config.packageName.replace('.', '/')
        return GeneratedFile(
            relativePath = "$directory/${Naming.fileNameFor(source.nameWithoutExtension)}",
            contents = out.toString(),
        ) to diagnostics
    }

    /**
     * The COPY text encoder, emitted once per package when any `:copy` query
     * exists. A generated helper rather than a runtime library, so the promise
     * of no pgd dependency at runtime still holds.
     */
    fun generateCopySupport(config: CodeGenConfig): GeneratedFile {
        val body = """
            |// Generated by pgd. Do not edit.
            |package ${config.packageName}
            |
            |/**
            | * Renders one value as a field in COPY text format.
            | *
            | * NULL is the two-character sequence \N, and backslash, tab, newline
            | * and carriage return are escaped so they cannot end the field or the
            | * row early.
            | */
            |internal fun pgdCopyText(value: Any?): String = when (value) {
            |    null -> "\\N"
            |    is Boolean -> if (value) "t" else "f"
            |    is ByteArray -> "\\\\x" + value.joinToString("") { "%02x".format(it) }
            |    else -> value.toString()
            |        .replace("\\", "\\\\")
            |        .replace("\t", "\\t")
            |        .replace("\n", "\\n")
            |        .replace("\r", "\\r")
            |}
            |
        """.trimMargin()
        return GeneratedFile("${config.packageName.replace('.', '/')}/PgdCopy.kt", body)
    }

    /** One file holding every enum the generated queries actually reference. */
    fun generateEnums(enums: List<EnumType>, config: CodeGenConfig): GeneratedFile? {
        if (enums.isEmpty()) return null
        val out = StringBuilder()
        out.append("// Generated by pgd. Do not edit.\n")
        out.append("package ${config.packageName}\n")
        enums.sortedBy { it.kotlin }.forEach { enum ->
            out.append("\nenum class ${enum.kotlin}(val label: String) {\n")
            enum.entries().forEach { (entry, label) -> out.append("    $entry(\"$label\"),\n") }
            out.append("    ;\n\n")
            out.append("    companion object {\n")
            out.append("        fun fromLabel(label: String): ${enum.kotlin} =\n")
            out.append("            entries.firstOrNull { it.label == label }\n")
            out.append(
                "                ?: error(\"'\$label' is not a value of Postgres enum " +
                    "${enum.postgresName}\")\n",
            )
            out.append("    }\n")
            out.append("}\n")
        }
        val directory = config.packageName.replace('.', '/')
        return GeneratedFile("$directory/Enums.kt", out.toString())
    }

    private class Model(val text: String, val imports: Set<String>)

    private fun modelOf(analyzed: AnalyzedQuery, registry: TypeRegistry): Pair<Model?, List<Diagnostic>> {
        val query = analyzed.query
        val diagnostics = mutableListOf<Diagnostic>()

        val params = analyzed.params.map { info ->
            val type = registry.resolve(info.typeName)
            if (type == null) {
                diagnostics += TypeMapper.unmapped(info.typeName, query, "parameter \$${info.index}")
                return@map null
            }
            Param(
                name = Naming.escape(Naming.lowerCamel(info.name ?: "param${info.index}")),
                type = type,
                index = info.index,
            )
        }

        val columns = analyzed.columns.map { info ->
            val type = registry.resolve(info.typeName)
            if (type == null) {
                diagnostics += TypeMapper.unmapped(info.typeName, query, "column '${info.label}'")
                return@map null
            }
            Column(
                property = Naming.propertyName(info.label),
                type = type,
                nullable = info.nullable,
                index = info.index,
            )
        }

        diagnostics += duplicates(params.filterNotNull().map { it.name }) { name ->
            Diagnostic(
                severity = Severity.ERROR,
                code = Diagnostic.DUPLICATE_PARAM_NAME,
                file = query.file.toString(),
                line = query.headerLine,
                query = query.name,
                message = "Query '${query.name}' has two parameters named '$name'.",
                hint = "Give each name on the `-- params:` line a distinct value.",
            )
        }
        diagnostics += duplicates(columns.filterNotNull().map { it.property }) { name ->
            Diagnostic(
                severity = Severity.ERROR,
                code = Diagnostic.DUPLICATE_COLUMN_LABEL,
                file = query.file.toString(),
                line = query.headerLine,
                query = query.name,
                message = "Query '${query.name}' returns two columns that both become '$name'.",
                hint = "Alias one of them, e.g. `SELECT u.id AS user_id, o.id AS order_id`.",
            )
        }

        if (diagnostics.isNotEmpty()) return null to diagnostics
        val resolvedColumns = columns.filterNotNull()
        if (query.cardinality.isCopy) return emitCopy(analyzed, resolvedColumns)
        return emit(analyzed, params.filterNotNull(), resolvedColumns) to diagnostics
    }

    private fun duplicates(names: List<String>, build: (String) -> Diagnostic): List<Diagnostic> =
        names.groupingBy { it }.eachCount().filterValues { it > 1 }.keys.sorted().map(build)

    private fun emit(analyzed: AnalyzedQuery, params: List<Param>, columns: List<Column>): Model {
        val query = analyzed.query
        val imports = mutableSetOf<String>()
        params.forEach { imports += it.type.imports }
        columns.forEach { imports += it.type.imports }

        val rowClass = query.name + "Row"
        val scalar = columns.singleOrNull()
        // A single non-null column collapses to the value itself. A single
        // nullable column keeps its wrapper for `:one`, so "no row" stays
        // distinguishable from "the value was NULL".
        val useScalar = scalar != null &&
            (query.cardinality != Cardinality.ONE || !scalar.nullable)

        // Wherever there is a row class there is also a mapper overload, and the
        // mapper form is the one that does the work: the data class form
        // delegates to it. A consumer with their own class -- @Serializable,
        // internal, whatever -- builds it straight off the ResultSet instead of
        // paying for a generated row they immediately throw away, and their
        // mapper's parameter list is a compile-time contract against the query.
        val mapped = query.cardinality.expectsRows && columns.isNotEmpty() && !useScalar
        // A parameter named `mapper` would shadow it, so take the first free name.
        val mapper = generateSequence("mapper") { it + "_" }
            .first { candidate -> params.none { it.name == candidate } }
        val ctor = if (mapped) mapper else null

        val out = StringBuilder()

        if (columns.isNotEmpty() && !useScalar) {
            out.append("data class $rowClass(\n")
            columns.forEach { out.append("    val ${it.property}: ${it.kotlinType},\n") }
            out.append(")\n\n")
        }

        val constant = Naming.constantName(query.name)
        out.append(sqlConstant(constant, analyzed.jdbcSql))
        out.append("\n\n")

        val element = when {
            mapped -> "T"
            useScalar -> scalar.kotlinType
            else -> rowClass
        }
        val returnType = when (query.cardinality) {
            Cardinality.EXEC -> null
            Cardinality.EXECROWS -> "Int"
            Cardinality.MANY -> "List<$element>"
            Cardinality.ONE -> if (useScalar) "${scalar.type.kotlin}?" else "$element?"
            Cardinality.EXACTLYONE -> element
            Cardinality.COPY -> error("COPY is emitted separately")
        }

        out.append(kdoc(query))
        val name = Naming.lowerCamel(query.name)
        val function = if (mapped) {
            buildString {
                append("fun <T : Any> Connection.$name(\n")
                params.forEach { append("    ${it.name}: ${it.type.kotlin},\n") }
                append("    $mapper: (\n")
                columns.forEach { append("        ${it.property}: ${it.kotlinType},\n") }
                append("    ) -> T,\n")
                append(")")
            }
        } else {
            "fun Connection.$name(" +
                params.joinToString(", ") { "${it.name}: ${it.type.kotlin}" } +
                ")"
        }

        val binds = binds(analyzed, params, indent = 8) { it.name }

        when (query.cardinality) {
            Cardinality.EXEC, Cardinality.EXECROWS -> {
                val suffix = if (returnType == null) " {" else ": $returnType ="
                out.append("$function$suffix\n")
                out.append("    prepareStatement($constant).use { statement ->\n")
                out.append(binds)
                out.append(
                    if (returnType == null) {
                        "        statement.execute()\n    }\n}\n"
                    } else {
                        "        statement.executeUpdate()\n    }\n"
                    },
                )
            }

            Cardinality.MANY -> {
                out.append("$function: $returnType =\n")
                out.append("    prepareStatement($constant).use { statement ->\n")
                out.append(binds)
                out.append("        statement.executeQuery().use { resultSet ->\n")
                out.append("            val rows = ArrayList<$element>()\n")
                out.append("            while (resultSet.next()) {\n")
                out.append("                rows += ${construct(useScalar, ctor, rowClass, columns, indent = 16)}\n")
                out.append("            }\n")
                out.append("            rows\n")
                out.append("        }\n    }\n")
            }

            Cardinality.EXACTLYONE -> {
                out.append("$function: $returnType =\n")
                out.append("    prepareStatement($constant).use { statement ->\n")
                out.append(binds)
                out.append("        statement.executeQuery().use { resultSet ->\n")
                out.append("            check(resultSet.next()) {\n")
                out.append(
                    "                \"${query.name} is declared :exactlyone but matched no rows\"\n",
                )
                out.append("            }\n")
                out.append("            val row = ${construct(useScalar, ctor, rowClass, columns, indent = 12)}\n")
                out.append("            check(!resultSet.next()) {\n")
                out.append(
                    "                \"${query.name} is declared :exactlyone but matched more " +
                        "than one row\"\n",
                )
                out.append("            }\n")
                out.append("            row\n")
                out.append("        }\n    }\n")
            }

            Cardinality.COPY -> error("COPY is emitted separately")

            Cardinality.ONE -> {
                out.append("$function: $returnType =\n")
                out.append("    prepareStatement($constant).use { statement ->\n")
                out.append(binds)
                out.append("        statement.executeQuery().use { resultSet ->\n")
                out.append("            if (!resultSet.next()) {\n")
                out.append("                null\n")
                out.append("            } else {\n")
                out.append("                val row = ${construct(useScalar, ctor, rowClass, columns, indent = 16)}\n")
                out.append("                check(!resultSet.next()) {\n")
                out.append(
                    "                    \"${query.name} is declared :one but matched more than one row\"\n",
                )
                out.append("                }\n")
                out.append("                row\n")
                out.append("            }\n")
                out.append("        }\n    }\n")
            }
        }

        if (mapped) out.append(delegate(query, name, params, rowClass))
        if (query.batch) out.append(batch(analyzed, params, constant))

        return Model(out.toString(), imports)
    }

    /**
     * The convenience overload: same query, mapped into the generated row class.
     * It exists so the common call site stays short, and so `Row` is a worked
     * example of the shape a hand-written class has to match.
     */
    private fun delegate(
        query: ParsedQuery,
        name: String,
        params: List<Param>,
        rowClass: String,
    ): String {
        val returnType = when (query.cardinality) {
            Cardinality.MANY -> "List<$rowClass>"
            Cardinality.ONE -> "$rowClass?"
            else -> rowClass
        }
        val signature = params.joinToString(", ") { "${it.name}: ${it.type.kotlin}" }
        val arguments = (params.map { it.name } + "::$rowClass").joinToString(", ")
        val header = "fun Connection.$name($signature): $returnType ="
        return buildString {
            append("\n/** Maps each row to [$rowClass]. */\n")
            if (header.length <= MAX_LINE) {
                append("$header\n")
            } else {
                append("fun Connection.$name(\n")
                params.forEach { append("    ${it.name}: ${it.type.kotlin},\n") }
                append("): $returnType =\n")
            }
            val call = "    $name($arguments)"
            if (call.length <= MAX_LINE) {
                append("$call\n")
            } else {
                append("    $name(\n")
                params.forEach { append("        ${it.name},\n") }
                append("        ::$rowClass,\n")
                append("    )\n")
            }
        }
    }

    /**
     * A second entry point that binds many rows through `addBatch`. Only for
     * statements with no result set, which is all JDBC batching supports.
     */
    private fun batch(analyzed: AnalyzedQuery, params: List<Param>, constant: String): String {
        val query = analyzed.query
        val single = params.singleOrNull()
        val paramsClass = query.name + "Params"
        val element = single?.type?.kotlin ?: paramsClass

        return buildString {
            if (single == null) {
                append("\ndata class $paramsClass(\n")
                params.forEach { append("    val ${it.name}: ${it.type.kotlin},\n") }
                append(")\n")
            }
            append("\n/** Batched form of [${Naming.lowerCamel(query.name)}]. */\n")
            append("fun Connection.${Naming.lowerCamel(query.name)}Batch(rows: Iterable<$element>): IntArray =\n")
            append("    prepareStatement($constant).use { statement ->\n")
            append("        for (row in rows) {\n")
            append(binds(analyzed, params, indent = 12) { if (single != null) "row" else "row.${it.name}" })
            append("            statement.addBatch()\n")
            append("        }\n")
            append("        statement.executeBatch()\n")
            append("    }\n")
        }
    }

    /**
     * Bulk load through `COPY ... FROM STDIN`, streamed rather than buffered, so
     * loading a large file does not mean holding it in memory.
     */
    private fun emitCopy(
        analyzed: AnalyzedQuery,
        columns: List<Column>,
    ): Pair<Model?, List<Diagnostic>> {
        val query = analyzed.query
        val unsupported = columns.filter { it.type.copyExpression(it.property, it.nullable) == null }
        if (unsupported.isNotEmpty()) {
            return null to unsupported.map { column ->
                Diagnostic(
                    severity = Severity.ERROR,
                    code = Diagnostic.COPY_FORM,
                    file = query.file.toString(),
                    line = query.headerLine,
                    query = query.name,
                    message = "Column '${column.property}' has a type pgd cannot write in COPY text format.",
                    hint = "Arrays are not supported by ${Cardinality.COPY.tag}. " +
                        "Use ${Cardinality.EXEC.tag} with `-- batch` instead.",
                )
            }
        }

        val imports = mutableSetOf("org.postgresql.PGConnection", "org.postgresql.copy.PGCopyOutputStream")
        columns.forEach { imports += it.type.imports }

        val rowClass = query.name + "Row"
        val constant = Naming.constantName(query.name)
        val function = Naming.lowerCamel(query.name)

        val out = StringBuilder()
        out.append("data class $rowClass(\n")
        columns.forEach { out.append("    val ${it.property}: ${it.kotlinType},\n") }
        out.append(")\n\n")
        out.append(sqlConstant(constant, analyzed.jdbcSql))
        out.append("\n\n")
        out.append(kdoc(query))
        out.append("fun Connection.$function(rows: Iterable<$rowClass>): Long {\n")
        out.append("    val copy = PGCopyOutputStream(unwrap(PGConnection::class.java), $constant)\n")
        out.append("    try {\n")
        out.append("        val out = copy.bufferedWriter()\n")
        out.append("        for (row in rows) {\n")
        columns.forEachIndexed { index, column ->
            val value = column.type.copyExpression("row.${column.property}", column.nullable)
            out.append("            out.write($value)\n")
            val separator = if (index == columns.lastIndex) "\\n" else "\\t"
            out.append("            out.write(\"$separator\")\n")
        }
        out.append("        }\n")
        out.append("        out.flush()\n")
        // endCopy returns the row count; getHandledRowCount is unusable once the
        // stream has been closed, because close() releases the operation.
        out.append("        return copy.endCopy()\n")
        out.append("    } catch (e: Throwable) {\n")
        out.append("        // Leaving the connection mid-COPY would break every later statement.\n")
        out.append("        runCatching { copy.cancelCopy() }\n")
        out.append("        throw e\n")
        out.append("    }\n")
        out.append("}\n")

        return Model(out.toString(), imports) to emptyList()
    }

    private fun binds(
        analyzed: AnalyzedQuery,
        params: List<Param>,
        indent: Int,
        name: (Param) -> String,
    ): String = analyzed.bindings.mapIndexed { position, original ->
        val param = params.first { it.index == original }
        " ".repeat(indent) + param.type.bind(position + 1, name(param)) + "\n"
    }.joinToString("")

    private fun construct(
        useScalar: Boolean,
        mapper: String?,
        rowClass: String,
        columns: List<Column>,
        indent: Int,
    ): String {
        if (useScalar) return read(columns.single())
        val pad = " ".repeat(indent + 4)
        return buildString {
            if (mapper == null) {
                append("$rowClass(\n")
                columns.forEach { append("$pad${it.property} = ${read(it)},\n") }
            } else {
                // Kotlin forbids named arguments when invoking a function type,
                // so these are positional and must stay in column order.
                append("$mapper(\n")
                columns.forEach { append("$pad${read(it)},\n") }
            }
            append(" ".repeat(indent))
            append(")")
        }
    }

    private fun read(column: Column): String = column.type.read(column.index, column.nullable)

    private fun kdoc(query: ParsedQuery): String = buildString {
        append("/**\n")
        append(" * ```sql\n")
        // `*/` inside the statement would close the comment early.
        query.sql.split("\n").forEach { append(" * ${it.replace("*/", "* /")}\n") }
        append(" * ```\n")
        append(" */\n")
    }

    private fun sqlConstant(name: String, sql: String): String {
        val lines = sql.split("\n")
        val literals = lines.mapIndexed { index, line ->
            val suffix = if (index < lines.lastIndex) "\\n" else ""
            "\"${escape(line)}$suffix\""
        }
        return "private const val $name: String =\n    " + literals.joinToString(" +\n        ")
    }

    private fun escape(text: String): String = text
        .replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("$", "\\$")
}
