package io.pgdescribe.core

import java.nio.file.Path
import kotlin.io.path.readText

public enum class Cardinality {
    /** Zero or more rows. */
    MANY,

    /** Exactly zero or one row. */
    ONE,

    /** Exactly one row; missing it is an error rather than a null. */
    EXACTLYONE,

    /** No result set. */
    EXEC,

    /** No result set; returns the affected row count. */
    EXECROWS,

    /** Bulk load through `COPY ... FROM STDIN`. */
    COPY,
    ;

    public val tag: String get() = ":" + name.lowercase()

    public val expectsRows: Boolean get() = this == MANY || this == ONE || this == EXACTLYONE

    /** COPY cannot be prepared, so it is analysed and generated by a different path. */
    public val isCopy: Boolean get() = this == COPY

    public companion object {
        public fun fromTag(tag: String): Cardinality? =
            entries.firstOrNull { it.tag.equals(tag, ignoreCase = true) }

        public val tags: String get() = entries.joinToString(", ") { it.tag }
    }
}

/**
 * One named statement lifted out of a `.sql` file.
 *
 * [sqlStartLine] is the 1-based line in [file] holding [sql]'s first character,
 * so a character offset reported by Postgres maps back to a real file position.
 */
public data class ParsedQuery(
    val name: String,
    val cardinality: Cardinality,
    val paramNames: List<String>,
    val nullableOverrides: Set<String>,
    val notNullOverrides: Set<String>,
    /** `-- batch` was requested, so a batching function is generated alongside. */
    val batch: Boolean,
    val sql: String,
    val file: Path,
    val headerLine: Int,
    val sqlStartLine: Int,
)

public data class QueryParseResult(
    val queries: List<ParsedQuery>,
    val diagnostics: List<Diagnostic>,
)

/**
 * Reads sqlc-style query files:
 *
 * ```sql
 * -- name: FindActiveUsers :many
 * -- params: since
 * SELECT ... WHERE created_at > $1::timestamptz;
 * ```
 *
 * The body stays valid SQL you can paste straight into psql, which is why
 * parameters are positional `$1` with an optional `-- params:` line naming them
 * for codegen rather than a `:name` syntax that psql would reject.
 */
public object QueryParser {

    private val HEADER = Regex("""^\s*--\s*name\s*:\s*(.*)$""")
    private val DIRECTIVE = Regex("""^\s*--\s*(params|nullable|notnull)\s*:\s*(.*)$""")
    private val FLAG = Regex("""^\s*--\s*(batch)\s*$""")
    private val IDENTIFIER = Regex("""^[A-Za-z_][A-Za-z0-9_]*$""")
    private val WHITESPACE = Regex("""\s+""")

    public fun parseFile(file: Path): QueryParseResult = parse(file.readText(), file)

    public fun parse(text: String, file: Path): QueryParseResult {
        val diagnostics = mutableListOf<Diagnostic>()
        val queries = mutableListOf<ParsedQuery>()
        val seen = mutableMapOf<String, Int>()

        var pending: Header? = null
        val body = mutableListOf<IndexedValue<String>>()
        var sawHeader = false

        fun error(line: Int, code: String, message: String, hint: String?, query: String? = null) {
            diagnostics += Diagnostic(
                severity = Severity.ERROR,
                code = code,
                file = file.toString(),
                line = line,
                query = query,
                message = message,
                hint = hint,
            )
        }

        fun flush() {
            val header = pending ?: return
            pending = null
            val kept = body.dropWhile { it.value.isBlank() }
            body.clear()

            if (kept.isEmpty()) {
                error(
                    header.line,
                    Diagnostic.EMPTY_QUERY,
                    "Query '${header.name}' has no SQL body.",
                    "Write the statement on the lines after the header, or delete the header.",
                    header.name,
                )
                return
            }

            val previous = seen.put(header.name, header.line)
            if (previous != null) {
                error(
                    header.line,
                    Diagnostic.DUPLICATE_QUERY_NAME,
                    "Duplicate query name '${header.name}' (already declared on line $previous).",
                    "Query names become function names, so they must be unique. Rename one of them.",
                    header.name,
                )
                return
            }

            val query = ParsedQuery(
                name = header.name,
                cardinality = header.cardinality,
                paramNames = header.paramNames,
                nullableOverrides = header.nullable,
                notNullOverrides = header.notNull,
                batch = header.batch,
                sql = kept.joinToString("\n") { it.value }.trimEnd().removeSuffix(";").trimEnd(),
                file = file,
                headerLine = header.line,
                sqlStartLine = kept.first().index + 1,
            )
            diagnostics += checkParams(query)
            queries += query
        }

        for ((index, raw) in text.lines().withIndex()) {
            val lineNo = index + 1

            val headerMatch = HEADER.matchEntire(raw)
            if (headerMatch != null) {
                flush()
                sawHeader = true
                pending = parseHeader(headerMatch.groupValues[1], lineNo, ::error)
                continue
            }

            val current = pending
            if (current != null && !current.bodyStarted) {
                val flag = FLAG.matchEntire(raw)
                if (flag != null) {
                    if (flag.groupValues[1] == "batch") current.batch = true
                    continue
                }

                val directive = DIRECTIVE.matchEntire(raw)
                if (directive != null) {
                    val values = directive.groupValues[2]
                        .split(',')
                        .map { it.trim() }
                        .filter { it.isNotEmpty() }
                    when (directive.groupValues[1]) {
                        "params" -> current.paramNames = values
                        "nullable" -> current.nullable = values.toSet()
                        "notnull" -> current.notNull = values.toSet()
                    }
                    continue
                }
            }

            if (current == null) {
                if (raw.isNotBlank() && !raw.trimStart().startsWith("--") && !sawHeader) {
                    sawHeader = true
                    error(
                        lineNo,
                        Diagnostic.ORPHAN_SQL,
                        "SQL found before any `-- name:` header.",
                        "Every statement needs a header, e.g. `-- name: FindUser :one`.",
                    )
                }
                continue
            }

            if (raw.isNotBlank()) current.bodyStarted = true
            body += IndexedValue(index, raw)
        }
        flush()

        return QueryParseResult(queries, diagnostics)
    }

    private fun parseHeader(
        rest: String,
        line: Int,
        error: (Int, String, String, String?, String?) -> Unit,
    ): Header? {
        val parts = rest.trim().split(WHITESPACE).filter { it.isNotEmpty() }
        val name = parts.getOrNull(0)
        if (name == null) {
            error(line, Diagnostic.MALFORMED_HEADER, "Header has no query name.", "Write `-- name: FindUser :one`.", null)
            return null
        }
        if (!IDENTIFIER.matches(name)) {
            error(
                line,
                Diagnostic.MALFORMED_HEADER,
                "'$name' is not a usable query name.",
                "Use a Kotlin-style identifier, e.g. `-- name: FindActiveUsers :many`.",
                null,
            )
            return null
        }
        val tag = parts.getOrNull(1)
        if (tag == null) {
            error(
                line,
                Diagnostic.MALFORMED_HEADER,
                "Query '$name' has no cardinality tag.",
                "Append one of ${Cardinality.tags}, e.g. `-- name: $name :many`.",
                name,
            )
            return null
        }
        val cardinality = Cardinality.fromTag(tag)
        if (cardinality == null) {
            error(
                line,
                Diagnostic.UNKNOWN_CARDINALITY,
                "Unknown cardinality tag '$tag' on query '$name'.",
                "Use one of ${Cardinality.tags}.",
                name,
            )
            return null
        }
        if (parts.size > 2) {
            error(
                line,
                Diagnostic.MALFORMED_HEADER,
                "Unexpected text after the cardinality tag on query '$name': ${parts.drop(2).joinToString(" ")}",
                "The header is exactly `-- name: <Name> <tag>`.",
                name,
            )
            return null
        }
        return Header(name, cardinality, line)
    }

    /**
     * Placeholder checks that need no database: are the declared names the right
     * count, and is the `$1..$n` run contiguous? The rewriter is used rather
     * than a bare regex so `$1` inside a string literal or comment is ignored.
     */
    private fun checkParams(query: ParsedQuery): List<Diagnostic> {
        val diagnostics = mutableListOf<Diagnostic>()
        val used = SqlRewriter.toJdbc(query.sql).distinct
        val highest = used.maxOrNull() ?: 0

        if (query.cardinality.isCopy && highest > 0) {
            diagnostics += Diagnostic(
                severity = Severity.ERROR,
                code = Diagnostic.COPY_FORM,
                file = query.file.toString(),
                line = query.headerLine,
                query = query.name,
                message = "Query '${query.name}' is declared ${Cardinality.COPY.tag} " +
                    "but uses placeholders.",
                hint = "COPY takes its data from the stream, not from parameters. " +
                    "The values come from the rows you pass in.",
            )
        }

        if (query.batch && query.cardinality.expectsRows) {
            diagnostics += Diagnostic(
                severity = Severity.ERROR,
                code = Diagnostic.BATCH_NOT_APPLICABLE,
                file = query.file.toString(),
                line = query.headerLine,
                query = query.name,
                message = "Query '${query.name}' is declared ${query.cardinality.tag}, " +
                    "which returns rows, so it cannot be batched.",
                hint = "JDBC batches only statements with no result set. " +
                    "Use ${Cardinality.EXEC.tag} or ${Cardinality.EXECROWS.tag}.",
            )
        }
        if (query.batch && highest == 0) {
            diagnostics += Diagnostic(
                severity = Severity.ERROR,
                code = Diagnostic.BATCH_NOT_APPLICABLE,
                file = query.file.toString(),
                line = query.headerLine,
                query = query.name,
                message = "Query '${query.name}' takes no parameters, so batching it would " +
                    "run the same statement repeatedly.",
                hint = "Remove `-- batch`, or add a placeholder that varies per row.",
            )
        }

        fun error(code: String, message: String, hint: String) {
            diagnostics += Diagnostic(
                severity = Severity.ERROR,
                code = code,
                file = query.file.toString(),
                line = query.headerLine,
                query = query.name,
                message = message,
                hint = hint,
            )
        }

        val missing = (1..highest).filterNot { it in used }
        if (missing.isNotEmpty()) {
            error(
                Diagnostic.PARAM_GAP,
                "Query '${query.name}' uses \$$highest but never uses " +
                    missing.joinToString(", ") { "\$$it" } + ".",
                "Postgres requires placeholders to run \$1..\$$highest with no gaps. " +
                    "Renumber them, or use the missing one.",
            )
        }

        if (query.paramNames.isNotEmpty() && query.paramNames.size != highest) {
            error(
                Diagnostic.PARAM_NAME_ARITY,
                "Query '${query.name}' declares ${query.paramNames.size} parameter name(s) " +
                    "but uses $highest placeholder(s).",
                if (highest > query.paramNames.size) {
                    "Add ${highest - query.paramNames.size} more name(s) to the `-- params:` line, " +
                        "in \$1..\$$highest order."
                } else {
                    "Remove the extra name(s) from the `-- params:` line."
                },
            )
        }

        return diagnostics
    }

    private class Header(
        val name: String,
        val cardinality: Cardinality,
        val line: Int,
    ) {
        var paramNames: List<String> = emptyList()
        var nullable: Set<String> = emptySet()
        var notNull: Set<String> = emptySet()
        var batch: Boolean = false
        var bodyStarted: Boolean = false
    }
}
