package io.pgdescribe.core

import kotlinx.serialization.json.Json

/**
 * Renders the catalog snapshot.
 *
 * `schema.md` exists so a session reads one current file instead of replaying
 * every migration to work out what the schema is now.
 */
public object SchemaWriter {

    private val json = Json {
        prettyPrint = true
        encodeDefaults = true
    }

    public fun toJson(catalog: PgCatalog): String =
        json.encodeToString(PgCatalog.serializer(), catalog) + "\n"

    public fun toMarkdown(catalog: PgCatalog): String = buildString {
        append("# Schema\n\n")
        append("Generated by pgd from the migrations. Do not edit; change a migration instead.\n")

        if (catalog.tables.isEmpty()) {
            append("\nNo tables.\n")
        }

        for (table in catalog.tables.sortedWith(compareBy({ it.schema }, { it.name }))) {
            append("\n## ${qualified(table.schema, table.name)}\n\n")
            append("| Column | Type | Null | Default |\n")
            append("| --- | --- | --- | --- |\n")
            for (column in table.columns) {
                val default = column.default?.let { "`${it.replace("|", "\\|")}`" } ?: ""
                append(
                    "| ${column.name} | `${column.type}` | " +
                        "${if (column.nullable) "yes" else "no"} | $default |\n",
                )
            }
            if (table.primaryKey.isNotEmpty()) {
                append("\nPrimary key: ${table.primaryKey.joinToString(", ") { "`$it`" }}\n")
            }
            for (unique in table.uniques) {
                append("\nUnique: ${unique.joinToString(", ") { "`$it`" }}\n")
            }
            for (key in table.foreignKeys) {
                append(
                    "\nForeign key: ${key.columns.joinToString(", ") { "`$it`" }} " +
                        "to `${key.targetTable}` " +
                        "(${key.targetColumns.joinToString(", ") { "`$it`" }})\n",
                )
            }
        }

        if (catalog.enums.isNotEmpty()) {
            append("\n## Enums\n\n")
            for (enum in catalog.enums.sortedWith(compareBy({ it.schema }, { it.name }))) {
                append(
                    "- `${qualified(enum.schema, enum.name)}`: " +
                        enum.labels.joinToString(", ") { "`$it`" } + "\n",
                )
            }
        }

        val domains = catalog.domains
        if (domains.isNotEmpty()) {
            append("\n## Domains\n\n")
            for (domain in domains.sortedBy { it.name }) {
                val notNull = if (domain.notNull) ", NOT NULL" else ""
                append("- `${domain.name}` over `${domain.baseType}`$notNull\n")
            }
        }
    }

    private fun qualified(schema: String, name: String): String =
        if (schema == "public") name else "$schema.$name"
}
